# Compatibility facade for the historical module name.
# Active model algebra lives under mms/model, post-solve processing under mms/postsolve,
# and workflow orchestration under mms/pipeline.

from mms.model.preprocessing import filter_generating_units, round_to_best, time_granularity, unit_categories
from mms.model.problem import define_problem_and_solve_problem
from mms.pipeline import parse_and_execute_optimization
from mms.postsolve import (
    APRR_violation,
    OOS_mode_constraints_violations,
    RES_PV_power_constraints_violations,
    availability_violations,
    create_output_json_template,
    extract_gen_hour,
    extract_numbers,
    extract_numbers_2,
    extract_numbers_3,
    extract_numbers_4,
    extract_single_value,
    forbidden_zones_violations,
    load_curtailment,
    matrices_to_dfs,
    max_transition_time_between_states_constraints_b_violations,
    min_state_transition_constraints_b_violations,
    min_transition_time_between_states_constraints_a_violations,
    min_transition_time_between_states_constraints_b_violations,
    mustRun_violations,
    output_json,
    pivot_df,
    ramp_up_down_violations,
    res_pv_constraints_violations,
    setpoint_calculation,
    solution_processing,
    testing_mode_constraints_violations,
    units_matrices,
)

__all__ = [
    "APRR_violation",
    "OOS_mode_constraints_violations",
    "RES_PV_power_constraints_violations",
    "availability_violations",
    "create_output_json_template",
    "define_problem_and_solve_problem",
    "extract_gen_hour",
    "extract_numbers",
    "extract_numbers_2",
    "extract_numbers_3",
    "extract_numbers_4",
    "extract_single_value",
    "filter_generating_units",
    "forbidden_zones_violations",
    "load_curtailment",
    "matrices_to_dfs",
    "max_transition_time_between_states_constraints_b_violations",
    "min_state_transition_constraints_b_violations",
    "min_transition_time_between_states_constraints_a_violations",
    "min_transition_time_between_states_constraints_b_violations",
    "mustRun_violations",
    "output_json",
    "parse_and_execute_optimization",
    "pivot_df",
    "ramp_up_down_violations",
    "res_pv_constraints_violations",
    "round_to_best",
    "setpoint_calculation",
    "solution_processing",
    "testing_mode_constraints_violations",
    "time_granularity",
    "unit_categories",
    "units_matrices",
]
